### ISSUE TITLE
commons.logging.LogConfigurationException

### ISSUE THREAD

**Issue by loopywolf** [baloise/dashboard-plus#5] opened 2015-10-15 17:35 UTC
Will the latest version work with 5.4?
If not, which version will work with 5.4?

Thanks

**Comment by greg-junkietech** [comment] 2015-10-16 11:15
Yes the latest version 1.2.9 availalble at [Atlassian Marketplace!](https://marketplace.atlassian.com/plugins/com.baloise.confluence.dashboard-plus/versions) should be compatible with Confluence 5.4.
Please make the experience and drop a feedback, thanks.

**Comment by loopywolf** [comment] 2015-10-22 15:03
Sonar Test Status is giving 'Error rendering macro 'sonar-test-status' : Could not initialize class org.apache.commons.httpclient.params.HttpConnectionManagerParams'

Jenkins Job Status is giving 'Runtime exception occured while retrieving information from Jenkins 2 https://jenkins-nowplay.touchtunes.com/, root cause:
org.apache.commons.logging.LogConfigurationException:
org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy. You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierachy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.) (Caused by org.apache.commons.logging.LogConfigurationException:
org.apache.commons.loggign.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.loggign.LogCongirationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.))

Any idea what's wrong? 
Confluence version is 5.4
Version of plugin is 1.2.9

**Comment by greg-junkietech** [comment] 2015-10-26 21:16
It seems that the commons-logging classes packaged in the plugin are causing the trouble on your installation because for some reason they are conflicting with another version already loaded by your confluence server.
Let me build a special plugin version for you without these commons-logging classes (1.2.9 light) and have a try again.

**Comment by loopywolf** [comment] 2015-10-26 21:23
Thanks!

Let me know when I can download

-AP

On Mon, Oct 26, 2015 at 5:16 PM, Gregory Laplace <notifications@github.com>
wrote:

> It seems that the commons-logging classes packaged in the plugin are
> causing the trouble on your installation because for some reason they are
> conflicting with another version already loaded by your confluence server.
> Let me build a special plugin version for you without these
> commons-logging classes (1.2.9 light) and have a try again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baloise/dashboard-plus/issues/5#issuecomment-151287106>
> .
>



-- 
Werewolves - scary on the outside, sweet on the inside

**Comment by greg-junkietech** [comment] 2015-10-27 12:16
Here you go: https://github.com/baloise/dashboard-plus/releases/download/atlassian_mp%2F1.2.9-no-commons-logging/dashboard-plus-1.2.9-no-commons-logging.jar

Thanks in advance for a feedback.

**Comment by greg-junkietech** [comment] 2015-11-02 10:50
Any feedback? Thanks in advance!

**Comment by greg-junkietech** [comment] 2016-06-16 11:56
Without feedback since fix from last october.
Assuming the problem is resolved, I am closing the issue now.

**Closed by greg-junkietech** 2016-06-16 11:56 UTC
