### ISSUE TITLE
Error rendering macro 'jenkins-job-status'

### ISSUE THREAD

**Issue by gclappc4** [baloise/dashboard-plus#1] opened 2014-10-20 19:29 UTC
Setting up the plugin to use one of my Jenkins Servers, I get this error: Error rendering macro 'jenkins-job-status' : com/offbytwo/jenkins/JenkinsServer

I have several Jenkins servers and the job is the correct name.

**Comment by greg-junkietech** [comment] 2015-01-27 22:43
Sorry for the answer delay.
You probably installed one of the first (buggy) version of the plugin from the Atlassian Marketplace as it was compiled partially, it resulted in ClassNotFoundException in your Confluence server logs.
We fixed this issue some weeks later, say about in last November.
Therefore I invite you to download the latest version from the Atlassian Marketplace and try again.

**Comment by greg-junkietech** [comment] 2015-10-16 11:08
Can I close this issue now?
Please give feedback wether the problem is fixed at your end, thanks.

**Comment by greg-junkietech** [comment] 2015-10-27 20:49
Any update on this issue?
This is a last call before I close it definitely by end of this week.
Thank you, regards.

**Closed** 2015-11-01 23:12 UTC
